### ISSUE TITLE
NumFrames() is 1 short preventing the last frame from viewing

### ISSUE THREAD

**Issue by oseredia** [marcel-goldschen-ohm/MultiPageTIFFViewerQt#2]
NumFrames is 1 short preventing the last frame from viewing. Adding 1 to self._tiffCaptureHandle.length on line 111 of MultiPageTIFFViewerQt.py fixes the problem

    def numFrames(self):
        """ Return the number of image frames in the stack.
        """
        if self._tiffCaptureHandle is not None:
            # !!! tiffcapture has length=0 for a single page TIFF.
            # If our handle is valid, we'll assume we have at least one image.
            return max([1, self._tiffCaptureHandle.length+1])
        return 0

**Comment by marcel-goldschen-ohm** [comment]
Thanks @oseredia! I'll aim to get this fix implemented in the next few days.

Cheers
